#!/usr/bin/python3

import argparse
import collections
import math
import os

from backend import apply_config, output_port_infos
from edid import info2edid, edid2ident, edid2size
from cfghelper import DesktopSetup as DESK
from cfghelper import OutputSetup as OUT
from config import postexec_all, defined_setups


def _output_matches(info, ident):
    """does the specified info match the given identifiers?"""
    known = edid2ident(info2edid(info))
    if known is None:
        return False
    if not isinstance(ident, list):
        ident = [ident]
    intersect = [x for x in ident if x in known]
    return len(intersect) > 0


def _get_outputs(infs):
    """return a description of all available outputs with connected monitors"""
    return [(port["name"], edid2ident(info2edid(port))) for port in infs]


def _inf4ident(infs, ident, allow_disconnected=False):
    """retrieve port name for given identifier.

    unless @allow_disconnected, only ports with a connection are searched.
    """
    for port in infs:
        if ident == port["name"]:
            if allow_disconnected or port["available_resolutions"]:
                return port
        if _output_matches(port, ident):
            if allow_disconnected or port["available_resolutions"]:
                return port
    return None


def _port4ident(infs, ident, allow_disconnected=False):
    """retrieve port name for given identifier.

    unless @allow_disconnected, only ports with a connection are searched.
    """
    i = _inf4ident(infs, ident, allow_disconnected)
    return i["name"] if i is not None else None


def _filter_valid_setups(infs, setups):
    valid = []
    for setup in setups:
        for output in setups[setup].outputs:
            if _inf4ident(infs, output.name) is None:
                break
        else:
            valid.append(setup)
    return valid


def _max_area_mode(modes):
    m = (0, 0)
    for mode in modes:
        if mode[0]*mode[1] > m[0]*m[1]:
            m = mode
    return m


def _max_width_mode(modes):
    m = (0, 0)
    for mode in modes:
        if mode[0] > m[0] or mode[0] == m[0] and mode[1] > m[1]:
            m = mode
    return m


def _apply_setup(infs, setup, dry=False):
    previous_port = None

    # keep order, otherwise some window manangers may get confused:
    outputs = collections.OrderedDict()

    # disable all output ports that are unused
    used_ports = [_port4ident(infs, output.name) for output in setup.outputs]
    for port in infs:
        if port["name"] not in used_ports:
            outputs[port["name"]] = None

    # prepare and validate settings, rescale to 0x0
    for output in setup.outputs:
        inf = _inf4ident(infs, output.name)

        cfg = {}
        cfg["port"] = _port4ident(infs, output.name)
        cfg["scale"] = output.scale
        cfg["rotate"] = output.rotation
        cfg["primary"] = output.primary

        cfg["location"] = output.location
        if isinstance(cfg["location"][0], str):
            if cfg["location"][1] == "previous":
                cfg["location"] = (cfg["location"][0], previous_port)
            cfg["location"] = (cfg["location"][0],
                               _port4ident(infs, cfg["location"][1]))
            if cfg["location"][1] is None:
                raise TypeError("invalid location '{}'".format(
                                                cfg["location"]))
        cfg["mode"] = output.mode
        if cfg["mode"] == "max_area":
            cfg["mode"] = _max_area_mode(inf["available_resolutions"])
        elif cfg["mode"] == "max_width":
            cfg["mode"] = _max_width_mode(inf["available_resolutions"])
        elif not isinstance(cfg["mode"], tuple):
            raise TypeError("invalid mode '{}'".format(cfg["mode"]))

        outputs[cfg["port"]] = cfg
        previous_port = cfg["port"]

    # translate given locations to absolute positions
    unresolved = True
    while unresolved:
        unresolved = False
        changed = False
        for (output, cfg) in outputs.items():
            if cfg is not None and isinstance(cfg["location"][0], str):
                other = outputs[cfg["location"][1]]
                if isinstance(other["location"][0], str):
                    unresolved = True
                else:
                    w, h = cfg["mode"]
                    w = int(w * cfg["scale"][0])
                    h = int(h * cfg["scale"][1])
                    if cfg["rotate"] in ("left", "right"):
                        h, w = w, h

                    ox, oy = other["location"]
                    ow, oh = other["mode"]
                    ow = int(ow * other["scale"][0])
                    oh = int(oh * other["scale"][1])
                    if other["rotate"] in ("left", "right"):
                        oy, ox = ox, oy
                        oh, ow = ow, oh

                    if cfg["location"][0] == "left-of":
                        x = ox - w
                        y = oy
                    elif cfg["location"][0] == "right-of":
                        x = ox + ow
                        y = oy
                    elif cfg["location"][0] == "above":
                        x = ox
                        y = oy - h
                    elif cfg["location"][0] == "below":
                        x = ox
                        y = oy + oh
                    else:
                        raise ValueError("unknown relative location {}".format(
                                         cfg["location"]))
                    cfg["location"] = (x, y)
                    changed = True

        if unresolved and not changed:
            print(outputs)
            raise ValueError("unable to resolve relative positioning")

    # normalize to (0, 0)
    offset_x = min((cfg["location"][0] for cfg in outputs.values()
                    if cfg is not None))
    offset_y = min((cfg["location"][1] for cfg in outputs.values()
                    if cfg is not None))
    for (port, cfg) in outputs.items():
        if cfg is not None:
            cfg["location"] = (cfg["location"][0] - offset_x,
                               cfg["location"][1] - offset_y)

    apply_config(outputs, postexec_all + setup.postexec, dry=dry)


def _res(w, h):
    if w == 0 or h == 0:
        return "off"
    return "{}x{}".format(w, h)


def _ratio16(w, h):
    """Aspect ratio of resolution, normalized to 16:x."""
    if w == 0 or h == 0:
        return "off"
    if w > h:
        return "16:" + str(round(16/w*h, 1)).replace(".0", "")
    else:
        return str(round(16/h*w, 1)).replace(".0", "") + ":16"


def _dpi(w, h, physsize):
    """DPI of w/h resolution on given physical display size"""
    if physsize:
        return int(math.sqrt(w**2+h**2)/
                   math.sqrt((physsize[0]/2.54)**2+(physsize[1]/2.54)**2))
    else:
        return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Display placer")
    parser.add_argument("selection", nargs='?')
    parser.add_argument("-a", "--auto", action="store_true",
                        help="try to pick a good choice")
    parser.add_argument("-f", "--fallback", action="store_true",
                        help="add a screen-maxing fallback configuration")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="show additional diagnostic and info")
    parser.add_argument("-V", "--veryverbose", action="store_true",
                        help="show all diagnostic and info")
    parser.add_argument("-d", "--dry", action="store_true",
                        help="only show what would be executed")
    args = parser.parse_args()
    verbose = args.verbose or args.veryverbose
    veryverbose = args.veryverbose

    infs = output_port_infos()

    if args.fallback:
        valid_outputs = sorted([inf for inf in infs
                                if len(inf["available_resolutions"]) > 0],
                               key=lambda i: i["name"])
        if len(valid_outputs) > 0:
            fb = DESK(OUT(valid_outputs[0]["name"], primary=True),
                      *[OUT(out["name"], location=("right-of", "previous"))
                        for out in valid_outputs[1:]],
                      postexec=[])
            defined_setups["FALLBACK"] = fb
            fbr = DESK(OUT(valid_outputs[-1]["name"], primary=True),
                      *[OUT(out["name"], location=("right-of", "previous"))
                        for out in valid_outputs[:-1]],
                      postexec=[])
            defined_setups["FALLBACKR"] = fbr

    valid_setups = _filter_valid_setups(infs, defined_setups)

    if args.selection is None and not args.auto:
        print("available ports:")
        for (port, display) in _get_outputs(infs):
            if display:
                inf = _inf4ident(infs, port, allow_disconnected=True)
                physsize = edid2size(info2edid(inf))
                if physsize:
                    widthcm, heightcm = physsize
                    diagonaltxt = '%.1f" ' % (math.sqrt(widthcm*widthcm+
                                                        heightcm*heightcm)/2.54)
                else:
                    diagonaltxt = ''
                w, h = inf["resolution"]
                mode = _res(w, h)
                if physsize and w != 0 and h != 0:
                    resinfo = " ({}, {}dpi)".format(
                                _ratio16(w, h), _dpi(w, h, physsize))
                else:
                    resinfo = ""
                print(" - {port}, {mode}{resinfo}, ".format(
                              port=port,
                              resinfo=resinfo,
                              mode=mode,)
                      + "connected to {diagonaltxt}{display}".format(
                              diagonaltxt=diagonaltxt,
                              display=display if verbose else display[0]))
                if verbose:
                    print("   has modes and ratios:")
                    for (w, h) in sorted(inf["available_resolutions"],
                                         key=lambda m: m[0]*m[1],
                                         reverse=True):
                        if physsize:
                            dpitxt = "{}dpi".format(_dpi(w, h, physsize))
                        else:
                            dpitxt = ""
                        print("     %-10s  %-10s %-10s" % (_res(w, h),
                                                           _ratio16(w, h),
                                                           dpitxt))
            else:
                print(" - {}".format(port))
        print()
        print("currently valid selections, in order of priority:")
        for s in valid_setups:
            print(" - {}".format(s))
            if verbose:
                print("    {}".format(defined_setups[s]))
        if args.veryverbose:
            print()
            print("currently invalid setups:")
            for s in defined_setups:
                if s not in valid_setups:
                    print(" - {}".format(s))
                    print("    {}".format(defined_setups[s]))
            print()
            if postexec_all:
                print("global postexec:")
                for p in postexec_all:
                    print("\t{}".format(p))
    else:
        if args.selection and args.auto:
            parser.error("cannot --auto and select")

        selection = args.selection
        if args.auto:
            valid_setups = _filter_valid_setups(infs, defined_setups)
            if valid_setups:
                selection = valid_setups[0]

        if selection not in defined_setups:
            parser.error("{} is not a known setup".format(selection))
        if selection not in valid_setups:
            parser.error("{} is currently not a valid setup".format(selection))

        print("picked configuration: {}".format(selection))
        if verbose:
            print(defined_setups[selection])
        _apply_setup(infs, defined_setups[selection], dry=args.dry)
